### ISSUE TITLE
typo in --help

### ISSUE THREAD

**Issue by matthiaskrgr** [Nilstrieb/cargo-minimize#4]
`      --verify-fn <VERIFY_FN>      A Rust closure returning a bool that checks whether a regression reproduces. Example: `--verify_fn='|output| output.contains("internal compiler error")'``

the second `verify_fn` should be `verify-fn`

**Comment by Nilstrieb** [comment]
Fixed in [8fc0693](https://github.com/Nilstrieb/cargo-minimize/commit/8fc0693cc3905e599c1ee41667160f2d7d930ea2) together with some other typos
