### ISSUE TITLE
wishlist: ability to point at specific rust/cargo builds with arbitrary command line flags

### ISSUE THREAD

**Issue by pnkfelix** [Nilstrieb/cargo-minimize#8]
I'm super excited to see work in this space. If nothing else, it looks like it brings back my beloved "everybody_loops" minimization step. :)

I tried using it today to cut down on 25 kloc source file, but unfortunately the ICE in question is connected to a locally built rustc, along with a slew of environment variables.

(In particular, the problem originates from the rust bootstrapping process, so the command line invocation looks like this:

```term
RUSTC_BOOTSTRAP=1 \
RUSTC_FORCE_UNSTABLE=1  \
RUSTC_BREAK_ON_ICE=1 \
RUSTC_LIBDIR="/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1/lib" \
RUSTC_REAL="/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" \
RUSTC_SNAPSHOT="/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" \
RUSTC_SNAPSHOT_LIBDIR="/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1/lib" \
RUSTC_STAGE="1" RUSTC_SYSROOT="/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1" \
/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/bootstrap/debug/rustc \
  /tmp/syn-1.0.102/src/lib.rs \
  --crate-name syn --edition=2018 \
  --crate-type lib \
  --cfg 'feature="full"' --cfg 'feature="parsing"' --cfg 'feature="printing"'  \
  -L dependency=/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps \
  --extern proc_macro2=/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/libproc_macro2-c375fd22c2a75927.rmeta \
  --extern quote=/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/libquote-da84683634313048.rmeta \
  --extern unicode_ident=/media/pnkfelix/Rust/rust.git/objdir-dbgopt/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps/libunicode_ident-5a2e42a7c2d6a19e.rmeta \
  --cap-lints allow -Z binary-dep-depinfo --cfg syn_disable_nightly_tests
```

(Note that the above has essentially four parts: 1. environment variables, 2. the "rustc" path (which in this case is the bootstrap rustc that dispatches to another rustc it grabs from the env vars), 3. the input file (`/tmp/syn-1.0.102/src/lib.rs`), and 4. all the other command line flags.)

It would be really slick if this tool could just input something like a shell-script invocation of the above and turn it into whatever it needs for its own purposes.

So far, my attempts to emulate this by using the existing `--env`, `--extra-args`, and `--rustc` flags (and overriding PATH in the hopes that would work to point at a different `rustc` build) have not worked out.

**Comment by Nilstrieb** [comment]
I have properly (hopefully, I didn't have too much time to test it) implemented the `--script-path` flag which should serve your use case. I've also added some examples to the readme.

**Comment by Nilstrieb** [comment]
I think I have to do a full minimization with it myself and adjust it while doing it before I can really say that it's usable :D
Feel free to PR changes or open further issues if you encounter more problems with it

**Comment by pnkfelix** [comment]
Hmm, how are other arguments that are passed to `cargo-minimize` handled when one uses the `--script-path` CLI parameter?

In particular, are there any environment variables injected by `cargo-minimize` that the script might want to observe, *or* command-line parameters that are themselves passed along to the given script? Or is the script always invoked with no parameters, and one must ensure that any desired parameters are embedded in the script itself (or extracted from the environment that the script invocation presumably inherits from the environment of the invocation of `cargo-minimize` itself)?

**Comment by Nilstrieb** [comment]
The script is run with `--extra-args` and it gets the `MINIMIZE_LINTS=1` env var when it should emit lints (it has to specify the way that it emits lints in the first line of the output, see the README for more info.

**Comment by Nilstrieb** [comment]
I've just used it to minimize an incremental ICE which needs some custom script setup and it worked well, so I'm closing this.
If you have further questions around how to use it, feel free to reopen an issue or ask on zulip.
